/**
 * build.js: the one build command.
 *
 *   node tools/build.js
 *
 * 1. Writes public/blog/post-index.json (generate-index.js).
 * 2. Fills every <!-- build:NAME --> ... <!-- /build:NAME --> region in
 *    public/**\/*.html. Anything inside those regions is overwritten, so
 *    never edit it by hand. Regions:
 *      footer    shared footer, with the current year
 *      posts     homepage post list (left empty when there are no posts)
 *      postnav   newer/older links on each post
 *      corrections  the list on /corrections/, from data/corrections.json
 *      contact   spelled-out email plus GitHub, Tangled, and LinkedIn links
 * 3. Writes public/_redirects from data/corrections.json.
 * 4. Writes public/feed.xml (generate-feed.js).
 *
 * It never touches <!-- words:NAME --> regions. Those hold Matt's words.
 */

const fs = require('fs');
const path = require('path');
const { ROOT, PUBLIC, readConfig, escapeHtml, displayDate, listHtmlFiles } = require('./lib');
const { generateIndex } = require('./generate-index');
const { generateFeed } = require('./generate-feed');

const CORRECTIONS_PATH = path.join(ROOT, 'data', 'corrections.json');
const REDIRECTS_PATH = path.join(PUBLIC, '_redirects');

function footerHtml(config) {
  const year = new Date().getFullYear();
  return [
    `<p>&copy; ${year} Matt Rude. Writing licensed under <a href="https://creativecommons.org/licenses/by/4.0/" rel="license">CC BY 4.0</a> unless noted. <a href="/feed.xml" class="rss-link" title="Subscribe to RSS feed"><img src="/assets/images/Feed-icon.svg" alt="RSS" class="rss-icon"> RSS Feed</a></p>`,
    `<p class="ai-note">Built with the help of AI. <a href="${config.repoUrl}/blob/main/STANDARDS.md">Read more</a></p>`,
  ].join('\n');
}

/**
 * Contact line. The address is written as "user at domain dot tld" inside an
 * element that carries the two parts as data attributes. The full address
 * never appears in the HTML; blog.js joins it in the browser.
 */
function contactHtml(config) {
  const { user, domain } = config.contact;
  const spelled = `${user} at ${domain.split('.').join(' dot ')}`;
  return `<p><span class="email" data-user="${escapeHtml(user)}" data-domain="${escapeHtml(domain)}">${escapeHtml(spelled)}</span>`
    + ` | <a href="${config.links.github}" target="_blank">GitHub</a>`
    + ` | <a href="${config.links.tangled}" target="_blank">Tangled</a>`
    + ` | <a href="${config.links.linkedin}" target="_blank">LinkedIn</a></p>`;
}

function postListHtml(posts) {
  if (posts.length === 0) return '';
  const items = posts.map(post => [
    '        <li class="post card">',
    `            <h3><a href="/blog/posts/${post.slug}">${escapeHtml(post.title)}</a></h3>`,
    `            <p class="post-meta"><time datetime="${post.date}">${displayDate(post.date)}</time></p>`,
    '        </li>',
  ].join('\n'));
  return [
    '<section class="blog-posts">',
    '    <h2>Latest Posts</h2>',
    '    <ul class="post-list">',
    ...items,
    '    </ul>',
    '</section>',
  ].join('\n');
}

function readCorrections() {
  return JSON.parse(fs.readFileSync(CORRECTIONS_PATH, 'utf8'));
}

/** Matt's text from corrections.json: escaped, blank lines become paragraphs. */
function paragraphs(text, className) {
  const cls = className ? ` class="${className}"` : '';
  return text.trim().split(/\n\s*\n/).map(p => `<p${cls}>${escapeHtml(p.trim())}</p>`);
}

/**
 * Corrections list. Empty reasons and an empty intro are left out, so the
 * page shows titles and dates only until Matt writes them.
 */
function correctionsHtml(corrections) {
  const entries = [...corrections.entries].sort((a, b) =>
    b.removed.localeCompare(a.removed) || b.published.localeCompare(a.published));
  if (entries.length === 0) return '';

  const lines = corrections.intro ? paragraphs(corrections.intro, 'corrections-intro') : [];
  lines.push('<ul class="corrections-list">');
  for (const entry of entries) {
    lines.push(
      '    <li class="card">',
      `        <h3>${escapeHtml(entry.title)}</h3>`,
      `        <p class="post-meta"><span>Published <time datetime="${entry.published}">${displayDate(entry.published)}</time></span> <span class="edit-divider">·</span> <span>Removed <time datetime="${entry.removed}">${displayDate(entry.removed)}</time></span></p>`,
      ...(entry.reason ? paragraphs(entry.reason).map(p => `        ${p}`) : []),
      '    </li>'
    );
  }
  lines.push('</ul>');
  return lines.join('\n');
}

/**
 * public/_redirects for Cloudflare Pages: every removed page, with and
 * without .html, goes to /corrections/ with a 301.
 */
function redirectsText(corrections) {
  const lines = ['# Generated by tools/build.js from data/corrections.json. Do not edit by hand.'];
  for (const entry of corrections.entries) {
    lines.push(`${entry.path}.html /corrections/ 301`, `${entry.path} /corrections/ 301`);
  }
  return lines.join('\n') + '\n';
}

function postNavHtml(posts, file) {
  const i = posts.findIndex(post => post.file === path.basename(file));
  if (i === -1) return '';
  const link = (post, label) =>
    `<a href="/blog/posts/${post.slug}"><span class="nav-label">${label}</span> <span class="nav-title">${escapeHtml(post.title)}</span></a>`;
  const newer = i > 0 ? link(posts[i - 1], 'Newer Post') : '';
  const older = i < posts.length - 1 ? link(posts[i + 1], 'Older Post') : '';
  if (!newer && !older) return '';
  return [
    '<nav class="post-navigation" aria-label="Other posts">',
    `    <div class="prev-post">${newer}</div>`,
    `    <div class="next-post">${older}</div>`,
    '</nav>',
  ].join('\n');
}

/**
 * Replace the inside of every build region in one file.
 * Output is the same every run for the same input, so a rebuild with
 * nothing new leaves git clean.
 */
function fillRegions(html, file, fillers) {
  return html.replace(
    /^([ \t]*)<!-- build:([\w-]+) -->[\s\S]*?<!-- \/build:\2 -->/gm,
    (match, indent, name) => {
      if (!fillers[name]) {
        throw new Error(`${path.relative(PUBLIC, file)}: unknown build region "${name}"`);
      }
      const content = fillers[name](file);
      const body = content
        ? content.split('\n').map(line => (line ? indent + line : line)).join('\n') + '\n'
        : '';
      return `${indent}<!-- build:${name} -->\n${body}${indent}<!-- /build:${name} -->`;
    }
  );
}

function build() {
  const config = readConfig();
  const corrections = readCorrections();
  const posts = generateIndex();

  const fillers = {
    footer: () => footerHtml(config),
    posts: () => postListHtml(posts),
    postnav: file => postNavHtml(posts, file),
    corrections: () => correctionsHtml(corrections),
    contact: () => contactHtml(config),
  };

  let changed = 0;
  for (const file of listHtmlFiles(PUBLIC)) {
    const before = fs.readFileSync(file, 'utf8');
    const after = fillRegions(before, file, fillers);
    if (after !== before) {
      fs.writeFileSync(file, after, 'utf8');
      changed++;
    }
  }
  console.log(`Pages: ${changed} file(s) updated`);

  fs.writeFileSync(REDIRECTS_PATH, redirectsText(corrections), 'utf8');
  console.log(`Redirects: ${corrections.entries.length * 2} rule(s) -> public/_redirects`);

  generateFeed(posts, config);
}

module.exports = { build, fillRegions, redirectsText, REDIRECTS_PATH };

if (require.main === module) {
  try {
    build();
  } catch (error) {
    console.error(`Build failed: ${error.message}`);
    process.exit(1);
  }
}
